/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as BookingRouteImport } from './routes/booking'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BookingConfirmationRouteImport } from './routes/booking_.confirmation'
import { Route as BookingCancelRouteImport } from './routes/booking_.cancel'

const BookingRoute = BookingRouteImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingConfirmationRoute = BookingConfirmationRouteImport.update({
  id: '/booking_/confirmation',
  path: '/booking/confirmation',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingCancelRoute = BookingCancelRouteImport.update({
  id: '/booking_/cancel',
  path: '/booking/cancel',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/booking': typeof BookingRoute
  '/booking/cancel': typeof BookingCancelRoute
  '/booking/confirmation': typeof BookingConfirmationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/booking': typeof BookingRoute
  '/booking/cancel': typeof BookingCancelRoute
  '/booking/confirmation': typeof BookingConfirmationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/booking': typeof BookingRoute
  '/booking_/cancel': typeof BookingCancelRoute
  '/booking_/confirmation': typeof BookingConfirmationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/booking'
    | '/booking/cancel'
    | '/booking/confirmation'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/booking'
    | '/booking/cancel'
    | '/booking/confirmation'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/booking'
    | '/booking_/cancel'
    | '/booking_/confirmation'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  BookingRoute: typeof BookingRoute
  BookingCancelRoute: typeof BookingCancelRoute
  BookingConfirmationRoute: typeof BookingConfirmationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/booking': {
      id: '/booking'
      path: '/booking'
      fullPath: '/booking'
      preLoaderRoute: typeof BookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking_/confirmation': {
      id: '/booking_/confirmation'
      path: '/booking/confirmation'
      fullPath: '/booking/confirmation'
      preLoaderRoute: typeof BookingConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking_/cancel': {
      id: '/booking_/cancel'
      path: '/booking/cancel'
      fullPath: '/booking/cancel'
      preLoaderRoute: typeof BookingCancelRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  BookingRoute: BookingRoute,
  BookingCancelRoute: BookingCancelRoute,
  BookingConfirmationRoute: BookingConfirmationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
